### ISSUE TITLE
Cascade lookup don't work

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#876] opened 2016-07-05 10:27 UTC
The cascadeField in lookup don't work. This also happens in the Serene Basic Sample (FilteredLookupOrderDetailDialog).

In SerenityScript the updateItems: function() calls this.getItems(lookup) that ever return zero items. It's a bug?

![cattura2](https://cloud.githubusercontent.com/assets/16304015/16581453/d35a68fe-42a9-11e6-813e-f87b7337c63d.PNG)

![cattura](https://cloud.githubusercontent.com/assets/16304015/16581459/d7fc269a-42a9-11e6-8f3d-46defeb1cadc.PNG)

This piece of code don't work 
```js
return new Enumerable(function () {   
    return new IEnumerator(
            function () { enumerator = ss.getEnumerator(ienum); },
            function () {
                var ok = enumerator.moveNext();
                return ok ? this.yieldReturn(enumerator.current()) : false;
            },
            function () {
                var disposable = ss.safeCast(enumerator, ss.IDisposable);
                if (disposable) {
                    disposable.dispose();
                }
            }
   );
});
```

**Comment by volkanceylan** [comment] 2016-07-07 09:53
It shouldn't be a bug. If cascade value is null or no items with cascade value, it should return empty list. This is by design.

**Comment by Estrusco** [comment] 2016-07-07 13:06
You can see this behavior in Filtered Lookup in Detail Dialog sample in Serene.

![cattura](https://cloud.githubusercontent.com/assets/16304015/16653179/9162b288-444f-11e6-994d-31814578eef2.PNG)

![cattura2](https://cloud.githubusercontent.com/assets/16304015/16653184/987ab052-444f-11e6-9777-491ea53427a3.PNG)

At moment I have find a workaround making an ProductLookupEditor and overriding cascadeItems method.

```js
namespace Serene.Northwind {

    @Serenity.Decorators.registerEditor()
    export class ProductLookupEditor extends Serenity.LookupEditorBase<ProductRow, Serenity.LookupEditorOptions> {

        constructor(hidden: JQuery, options: Serenity.LookupEditorOptions) {
            super(hidden, options);
        }

        protected getLookupKey() {
            return 'Northwind.Product';
        }

        protected cascadeItems(items) {
            var cascadeItems = super.cascadeItems(items);

            if (this.cascadeValue === undefined)
                return cascadeItems;
            return items.filter(xi => xi.CategoryID == this.cascadeValue);
        }
    }
}
```

**Comment by volkanceylan** [comment] 2016-07-07 14:17
It's about CascadeField not defined as an ES5 property while converting to TypeScript. Fixed in 2.2.7

**Closed by volkanceylan** 2016-07-07 14:17 UTC

**Comment by Estrusco** [comment] 2016-07-07 20:01
Thank you!

**Comment by weiguanhai** [comment] 2016-07-21 02:24
Have you solved this proble about cascade? If solved, I need your help, Really thank you!
@Estrusco

**Comment by jsbUSMC** [comment] 2016-07-21 03:25
Update your nuget packages. 2.2.7 fixed this

**Comment by Estrusco** [comment] 2016-07-21 06:27
As said volkanceylan and jsbUSMC  this fidex in version 2.2.7
