### ISSUE TITLE
Timeout with serenity crafted queries

### ISSUE THREAD

**Issue by aksingh1979** [volkanceylan/Serenity#2181] opened 2017-04-22 11:58 UTC
My grid view has joins and and some expressions. When I see the query in SQL Profiler and run the same in SQL it works very slow but if I do minor tweaks to query it works extreme fast.

Can you please suggest a way where in I can modify the crafted query and send the one i tweaked by changing its where clause. To give you an example...one column is expression based such as
CASE WHEN JoinDate is NULL then 1 ELSE 0 END. I notice this becomes part of SELECT as well as WHERE clause. In where clause it looks like (CASE WHEN JoinDate is NULL then 1 ELSE 0 END)=@p1 when filter is applied on it.  I would like to leave the SELECT part but would like the WHERE part to be something like JoinDate Is Not Null or JoinDate is Null based on filter.

Please advice

**Comment by abelal83** [comment] 2017-04-23 08:44
I believe the sql used by serenity is based off of dapper. Perhaps take a look at dapper docs?

Sorry can't be of no more help, writing this from my phone.

**Comment by arunkumar12712** [comment] 2017-04-23 19:52
Below query runs within seconds in DB but serenity takes 3minutes or sometime more to display results. Please advice if I am missing anything
SELECT TOP 500 
T0.[Id] AS [Id],
T0.[TokenNo] AS [TokenNo],
T0.[PartyId] AS [PartyId],
T0.[ReceivedOn] AS [ReceivedOn],
T0.[PaidOn] AS [PaidOn],
T0.[LedgerId] AS [LedgerId],
T0.[ChkNeftRefNo] AS [ChkNeftRefNo],
T0.[Narration] AS [Narration],
T0.[VoucherId] AS [VoucherId],
T0.[Remarks] AS [Remarks],
T0.[MCode] AS [MCode],
T0.[OtherDeduction] AS [OtherDeduction],
T0.[OtherDeductionRemarks] AS [OtherDeductionRemarks],
T0.[ForceDeductTDS] AS [ForceDeductTDS],
T0.[PaymentMode] AS [PaymentMode],
jPaymentMode.[Name] AS [PaymentModeMode],
T0.[TDSDeclaration] AS [TDSDeclaration],
jParty.[PartyName] AS [PartyPartyName],
jParty.[ContactNo] AS [PartyContactNo],
jParty.[BankACNo] AS [PartyBankAcNo],
jParty.[IFSCCode] AS [IFSCCode],
jLedger.[LedgerName] AS [LedgerLedgerName],
T0.[Attachments] AS [Attachments],
jVoucher.[VoucherNo] AS [VoucherVoucherNo],
CASE When VoucherId IS Null Then 0 Else 1 END AS [VocuherStatus],
T0.[TokenStatus] AS [Status],
T0.[TokenBranchId] AS [TokenBranchId],
T0.[Amount] AS [Amount],
T0.[IsLock] AS [IsLock],
T0.[DiscounterId] AS [DiscounterId],
jRecovery.[Amount] * -1 AS [RecoverAdjustment],
T0.[RecoveryId] AS [RecoveryId],
T0.[FY] AS [FY],
T0.[InsertUserId] AS [InsertUserId],
T0.[InsertDate] AS [InsertDate],
T0.[UpdateUserId] AS [UpdateUserId],
T0.[UpdateDate] AS [UpdateDate] 
FROM [dbo].[Tranzol_Token] T0 
LEFT JOIN [dbo].[Accounts_PaymentMode] jPaymentMode ON (jPaymentMode.[Id] = T0.[PaymentMode]) 
LEFT JOIN [dbo].[Common_Parties] jParty ON (jParty.[Id] = T0.[PartyId]) 
LEFT JOIN [dbo].[Accounts_Ledgers] jLedger ON (jLedger.[Id] = T0.[LedgerId]) 
LEFT JOIN [dbo].[Accounts_Vouchers] jVoucher ON (jVoucher.[Id] = T0.[VoucherId]) 
LEFT JOIN [dbo].[Tranzol_Recovery] jRecovery ON (jRecovery.[Id] = T0.[RecoveryId]) 
WHERE ((T0.[FY] = @p1) AND (T0.[TokenBranchId] IN (4048,4043,4050,4034,4036,4037,4038,4047,4044,4030,4049,4051,4052,4031,4032,4042,4028,4041,4029))
ORDER BY T0.[ReceivedOn] DESC, T0.[Id] DESC;

**Comment by abelal83** [comment] 2017-04-24 06:22
@arunkumar12712 I'm no SQL expert but the query looks OK, have you tried running directly through dapper?

**Comment by aksingh1979** [comment] 2017-04-25 08:19
@abelal83 Thanks, I tried sample using dapper and experienced the same. Can you please advice an way around?

**Comment by abelal83** [comment] 2017-04-25 08:32
@arunkumar12712 sorry but I don't think I can help beyond this. As it looks to be dapper specific perhaps best to close this issue and raise issue on dapper github (https://github.com/StackExchange/Dapper). if you do find the cause would be great for you to share here too.

**Closed** 2017-04-26 20:13 UTC
