### ISSUE TITLE
Grid not showing

### ISSUE THREAD

**Issue by Gone4Coding** [volkanceylan/Serenity#2813] opened 2017-10-24 20:48 UTC
I had the need to create an editor for my dialog, but now my the grid is not showing.
![capture](https://user-images.githubusercontent.com/18728780/31967188-0f8a9740-b905-11e7-94f2-41bef2ee6c40.PNG)

**Comment by javaman63** [comment] 2017-10-25 14:34
you have this on the top of your xyzEditorDialog.ts

/// <reference path="../../Common/Helpers/GridEditorDialog.ts" />

???

**Comment by javaman63** [comment] 2017-10-25 14:40
you have this on the top of your xyzEditorDialog.ts?
![copia](https://user-images.githubusercontent.com/8239681/32004878-398dad24-b979-11e7-8f4e-f2da18df684e.png)

**Comment by javaman63** [comment] 2017-10-25 14:42
you have this on the top of your xyzEditorDialog.ts?
![copia](https://user-images.githubusercontent.com/8239681/32004994-88859932-b979-11e7-876c-4265ffef0336.png)

**Comment by Estrusco** [comment] 2017-10-26 08:47
I have the same issue in some grid after updating at version 3.2.2.

**Comment by brunobola** [comment] 2017-11-01 18:40
This is Fixed in last release...

**Comment by volkanceylan** [comment] 2017-11-13 06:17
Closing due to inactivity and non reproducability.

**Closed by volkanceylan** 2017-11-13 06:17 UTC
