### ISSUE TITLE
validation makes required field red (3.13.7) even if it has value

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#5125] opened 2020-07-26 21:19 UTC
I have required lookup field in dialog, that even when filled/selected gets colored red on explicit call of validation

`this.validateForm()`

this.validateForm() luckily returns true, so it's possible to submit form.

This was not the case 3.13.4. So the error was introduced somewhere in last 3 versions. Any idea how to fix this?
We are talking about Int16 field here

If there is no value selected, red mark with white cross appears (along with red bkg of dropdown), and form wont submit, which is expected behavior.

**Comment by volkanceylan** [comment] 2020-07-27 15:50
I don't see such behavior on Serenity demo, order dialog

**Comment by mustafalotiya** [comment] 2020-07-29 13:35
![image](https://user-images.githubusercontent.com/23294782/88806742-dd4e2200-d1c1-11ea-8c3b-7e27450f2caf.png)

**Comment by mustafalotiya** [comment] 2020-07-29 13:37
Above two drop down [lookupupeditr] has value still shows red highlighted mark. 

While estimated rate is mandatory (decimal field) works as usual.

**Comment by volkanceylan** [comment] 2020-07-29 20:29
Hmm, ok will try to reproduce this.

**Comment by volkanceylan** [comment] 2020-08-06 15:51
Should be resolved in 3.14.0

**Comment by minhhungit** [comment] 2020-08-06 16:37
after upgrading to 3.14.0 it works for me

**Closed** 2020-08-07 20:55 UTC

**Comment by ga5tan** [comment] 2020-08-07 21:15
works for me too, thx
