### ISSUE TITLE
filter operator 'contains' using 'startswith'

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#5240] opened 2020-10-06 09:25 UTC
Hey
quickfilter/advanced filter (pop up from grid) on a text field uses startswith even when 'contains' is selected.
this was reported a long time ago: 
[https://github.com/volkanceylan/Serenity/issues/3353](https://github.com/volkanceylan/Serenity/issues/3353)

maybe im missing some option, i was looking couldnt find.

any help?
thanks

**Comment by shakazulu89** [comment] 2020-10-12 08:08
nobody is having this issue?

**Comment by VictorTomaili** [comment] 2020-10-12 08:40
Do you post screenshot of this? I can't reproduce this case. 
![image](https://user-images.githubusercontent.com/2023440/95724084-97f8a700-0c7e-11eb-9ed0-7aa872f3d906.png)

**Comment by shakazulu89** [comment] 2020-10-12 09:24
listingrow:
`[DisplayName("Legacy Status"), Column("txtStatus"), ReadOnly(true)] 
        public String TxtStatus
        {
            get { return Fields.TxtStatus[this]; }
            set { Fields.TxtStatus[this] = value; }
        }`

column:

`
        [QuickFilter(CssClass = "hidden-xs")]
        public String TxtStatus { get; set; }`

just to show records exist with "Review" in them
![filterissue1](https://user-images.githubusercontent.com/1382996/95729363-15231c80-0c7d-11eb-957f-ea81b0bf9a9c.PNG)

when i use advanced filter or quickfilter nothing shows up unless i write "Peer Review" exactly.. 

![filterissue2](https://user-images.githubusercontent.com/1382996/95729376-181e0d00-0c7d-11eb-8603-99ae61e8cf09.PNG)

you can see in the service request it searches as "starts with"

![filterissue3](https://user-images.githubusercontent.com/1382996/95729382-1a806700-0c7d-11eb-9e5f-321c8541c0b5.PNG)

**Comment by VictorTomaili** [comment] 2020-10-12 14:41
It's working on serene demo as expected. You need ensure you doesn't override something wrong. Check your serenity version for latest one also. Try to create new project with serene and check same scenario for reproduce.   

![image](https://user-images.githubusercontent.com/2023440/95758879-a8764500-0cb1-11eb-9e5d-5b5290f302f4.png)
![image](https://user-images.githubusercontent.com/2023440/95758937-bcba4200-0cb1-11eb-9d9b-400611d9990d.png)

**Comment by shakazulu89** [comment] 2020-10-13 18:17
ok i just confirmed this is happening on all grids even the most simple ones. but in my other app thats using a newer version of serene it works fine. is there anyway to find out which version fixed this maybe i can grab that code... it wont be so easy for me to update the whole version of  serene...

**Comment by VictorTomaili** [comment] 2020-10-13 18:19
Check to nuget package versions and compare them from github commit history. Then check possible changesets in this range. 
Don't forget close issue if it's ok for you.

**Comment by shakazulu89** [comment] 2020-10-13 18:20
thanks for the quick reply man i really appreciate your help. what files should i be on the lookout that could effect this?

**Comment by VictorTomaili** [comment] 2020-10-13 21:37
request is sent by javascript. so you can check *.ts files.

**Comment by luongnv6** [comment] 2020-10-14 03:15
Hope this will help you

on xyzGrid.ts
```C#
 protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            // get quick filter list from base class, e.g. columns
            let filters = super.getQuickFilters();


            let fld = xyzRow.Fields;

            let filter = Q.first(filters, x => x.field == fld.TxtStatus);
            filter.title = "Section";
            filter.type = Serenity.StringEditor;
            filter.handler = h => {
                if (h.active) {
                    h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
                        [['TxtStatus'], 'like', '%' + h.value + '%']);
                }
            };

            return filters;
        }

**Comment by shakazulu89** [comment] 2020-10-14 08:45
ok pretty sure its this commit: [ added missing return statement that causes switch on contains to fall… ](https://github.com/volkanceylan/Serenity/commit/495eb0eca8a0ff7ad265d2cf2bbf97f9ccfe27b9)

but how can i edit this file in my existing project without having to update serene libraries (which will force me to create a new project etc.), any suggestions?

**Comment by VictorTomaili** [comment] 2020-10-14 09:36
Javascript code can be overridden. So you can override like this. 

```
Serenity.BaseFiltering.prototype.getCriteria = function() {
            var e = {};
            var i;
            switch (this.get_operator().key) {
            case "true":
                {
                    e.displayText = this.displayText(this.get_operator(), []);
                    e.criteria = [[this.getCriteriaField()], "=", true];
                    return e
                }
            case "false":
                {
                    e.displayText = this.displayText(this.get_operator(), []);
                    e.criteria = [[this.getCriteriaField()], "=", false];
                    return e
                }
            case "isnull":
                {
                    e.displayText = this.displayText(this.get_operator(), []);
                    e.criteria = ["is null", [this.getCriteriaField()]];
                    return e
                }
            case "isnotnull":
                {
                    e.displayText = this.displayText(this.get_operator(), []);
                    e.criteria = ["is not null", [this.getCriteriaField()]];
                    return e
                }
            case "contains":
                {
                    i = this.getEditorText();
                    e.displayText = this.displayText(this.get_operator(), [i]);
                    e.criteria = [[this.getCriteriaField()], "like", "%" + i + "%"];
                    return e
                }
            case "startswith":
                {
                    i = this.getEditorText();
                    e.displayText = this.displayText(this.get_operator(), [i]);
                    e.criteria = [[this.getCriteriaField()], "like", i + "%"];
                    return e
                }
            case "eq":
            case "ne":
            case "lt":
            case "le":
            case "gt":
            case "ge":
                {
                    i = this.getEditorText();
                    e.displayText = this.displayText(this.get_operator(), [i]);
                    e.criteria = [[this.getCriteriaField()], t.FilterOperators.toCriteriaOperator[this.get_operator().key], this.getEditorValue()];
                    return e
                }
            }
            throw new ss.Exception(Q.format("Filtering '{0}' has no handler for '{1}' operator", ss.getTypeName(ss.getInstanceType(this)), this.get_operator().key))
}
```

**Comment by shakazulu89** [comment] 2020-10-14 09:39
hm cool i never did that.. noob question, where is the best place to put this code?

**Comment by VictorTomaili** [comment] 2020-10-14 09:44
Layout preferred after other scripts installed. I close this issue, because it's fixed and old bug. For any other questions you can use stackoverflow with serenity-platform tag. 
https://stackoverflow.com/tags/serenity-platform

**Closed by VictorTomaili** 2020-10-14 09:44 UTC

**Comment by shakazulu89** [comment] 2020-10-14 10:03
@VictorTomaili ok man again i really appreciate it!!

**Comment by tmartinscopo** [comment] 2022-09-08 11:48
@shakazulu89 Hi! Where did you place the code?

**Comment by ali-h2010** [comment] 2023-05-23 11:34
I am facing this issue with QuickFilters
it's using = instead of like in the sql query

WHERE (c.[First Name] ) = @p1)

**Comment by ali-h2010** [comment] 2023-05-23 12:11
> Hope this will help you
> 
> on xyzGrid.ts
> 
> ```cs
>  protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
> 
>             // get quick filter list from base class, e.g. columns
>             let filters = super.getQuickFilters();
> 
> 
>             let fld = xyzRow.Fields;
> 
>             let filter = Q.first(filters, x => x.field == fld.TxtStatus);
>             filter.title = "Section";
>             filter.type = Serenity.StringEditor;
>             filter.handler = h => {
>                 if (h.active) {
>                     h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
>                         [['TxtStatus'], 'like', '%' + h.value + '%']);
>                 }
>             };
> 
>             return filters;
>         }
> ```

I am getting an error Serentiy and Q are not found
