### ISSUE TITLE
InvalidCastException error comes while saving Time field

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#738] opened 2016-05-27 10:54 UTC
I have created migration with following code
`[Migration(20160527155000)]
    public class DefaultDB_20160527_155000_Creating_Test_Table : AutoReversingMigration
    {
        public override void Up()
        {
            Create.Table("Test")
                .WithColumn("Id").AsInt32().Identity().PrimaryKey().NotNullable()
                .WithColumn("PunchTime").AsTime().NotNullable();
        }
    }`
generated code with sergen.
When trying to save entity, it raises InvalidCastException as follows 
 
An exception of type 'System.InvalidCastException' occurred in Serenity.Data.dll but was not handled in user code
Additional information: Failed to convert parameter value from a TimeSpan to a DateTime.
regards
Shailesh

**Comment by volkanceylan** [comment] 2016-05-27 13:48
You need to use a TimeSpanField for your column

**Comment by shaileshbc** [comment] 2016-05-28 04:04
Following code generated using Sergen
`[ConnectionKey("Default"), DisplayName("Test"), InstanceName("Test"), TwoLevelCached]
    [ReadPermission("Administration")]
    [ModifyPermission("Administration")]
    public sealed class TestRow : Row, IIdRow
    {
        [DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Punch Time"), NotNull]
        public TimeSpan? PunchTime
        {
            get { return Fields.PunchTime[this]; }
            set { Fields.PunchTime[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public TestRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public TimeSpanField PunchTime;

            public RowFields()
                : base("[dbo].[Test]")
            {
                LocalTextPrefix = "Master.Test";
            }
        }`
`[FormScript("Master.Test")]
    [BasedOnRow(typeof(Entities.TestRow))]
    public class TestForm
    {
        public TimeSpan PunchTime { get; set; }
    }`
`[ColumnsScript("Master.Test")]
    [BasedOnRow(typeof(Entities.TestRow))]
    public class TestColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 Id { get; set; }
        public TimeSpan PunchTime { get; set; }
    }`
still i am getting same error when trying to insert 10:00:00 in PunchTime field.
Thanks in advance
regards
Shailesh

**Comment by volkanceylan** [comment] 2016-05-28 15:37
This was caused by ADO.NET changing parameter type to DateTime when you set it to Time! Probably because Time was added in SQL 2008. Should be fixed in 2.2.1.

**Closed by volkanceylan** 2016-05-28 15:37 UTC
