### ISSUE TITLE
Validations does not work as expected within the Popup Dialogues

### ISSUE THREAD

**Issue by PAAutofac** [volkanceylan/Serenity#4576] opened 2019-08-23 10:31 UTC
Validations does not work as expected on pop up Dialogue eg: Add new record.
I am referring to attribute "Not Null" .

Demo project eg Northwind -> Products ->(New Product) -> New product pop up dialogue is displayed .
User clicks save button without any inputs . 
Required fields are : Product Name, Units In Stock, Units On Order and Reorder Level 
If you remove the default values displayed for Units In Stock,Units On Order and Reorder Level and click save button, the error tooltip is not displayed  for all required fields.

Is it a known issue?

While using Not Null - ideally I was expecting the editor to change the colour to RED and the tooltip message as "This field is required" for all fields within the Form/Popup Dialogue.

Thanks

Thanks

**Comment by hubeyb** [comment] 2019-11-21 12:39
Duplicate of #4573

**Closed** 2020-03-10 11:33 UTC
