### ISSUE TITLE
[Help Requested] LanguagePreference Cookie behavior 

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#5229] opened 2020-09-26 19:59 UTC
hey there Volkan,

I have a Strange behavior with Application_BeginRequest (in order to take into account current language selection).
The issue i have is that it seems that LanguagePreference cookie in Application_BeginRequest is different depending on the pages it's called from.
I have 2 cookies with this name and when Calling cookie.Value, the browser seems to determine which value he is using.

After browsing some URLs, i noticed i have one cookie is having different access path (to "/" and another one to "/Factory") (with same name = LanguagePreference).
I started StartSharp app from scratch and noticed i keep the LanguagePreference along with Path (so if i changed language on a screen by mistake i keep this settings until i change it).
=> Seems like i am discovering this today. I Always thought language preference was for whole site (not associated to an URL).

Did i miss Something ? 

Easy way to reproduce this (with a new StartSharp application) : 

go to Dashboard menu -> change to Russian
![image](https://user-images.githubusercontent.com/31513956/94349273-3829bb80-0043-11eb-9dae-8c1301e0051e.png)

go to Administration / User Management menu -> change to Turkish
![image](https://user-images.githubusercontent.com/31513956/94349286-5bed0180-0043-11eb-9bec-f6cb15cdc50f.png)

go to Dashboard menu => language switched back to Russian automatically
go to Administration / User Management menu ->  language switched back to Turkish

This seems especially disturbing for a user, is there a way to keep the LanguagePreference setting for the whole site ? 
(path = Q.Config.applicationPath)

=> i have tried same test with Serenity.is/demo but it works correctly (change of language Apply to whole site and there is no automatic switching to another language when changing of menu).
Is there Something incorrect in the StartSharp/Serene Template ?

**Comment by VictorTomaili** [comment] 2020-09-26 21:15
`Q.Config.applicationPath` gets it value from `_LayoutHead.cshtml` can you check this value? `<link rel="home" id="ApplicationPath" href="~/" />`

**Comment by kilroyFR** [comment] 2020-09-26 21:21
yes it"s :  (i did create StartSharp project with wizard without any other modifications)

`<link rel="home" id="ApplicationPath" href="~/" />`

**Comment by volkanceylan** [comment] 2020-09-28 21:06
Try setting Q.Config.applicationPath = '/' in your ScriptInitialization.ts, but clear all your localhost cookies before trying

**Comment by volkanceylan** [comment] 2020-09-28 21:08
It's not a normal feature, probably was caused by some change in Q.Config.ts that should hopefully be changed by this commit: aa3a600b9806640decdfd6115dcbabf1b8c6a1ff

**Comment by kilroyFR** [comment] 2020-09-28 21:15
> Q.Config.applicationPath = '/'

This trick worked (after cleanup cookies). Thanks again Volkan

**Comment by kilroyFR** [comment] 2020-10-16 09:24
Volkan, using the Tip : 
Q.Config.applicationPath = '/'

it's working nicely locally but when i publish the website et try to connect on the application i am getting an error 404 when trying to access Lookup.Administration/Language.js

**Comment by VictorTomaili** [comment] 2020-10-16 09:27
Can you post your question on stackoverflow with [serenity-platform](https://stackoverflow.com/questions/tagged/serenity-platform) tag? 
404 error is different than main topic and we want to clear questions from issues.

**Comment by kilroyFR** [comment] 2020-10-16 09:36
@VictorTomaili it's a real serenity error to me and i am startsharp user. 
When i remove the fix (Q.Config.applicationPath = '/') 
=> it's working (but with the initial issue related to cookie keeping language preference with URI) that was not a normal feature.

I did test the modification Volkan did on the Q.Config.ts but it does not work.
Do basically this issue is still pending for me.

**Comment by kilroyFR** [comment] 2020-10-16 09:48
Remember Volkan answer : 
"It's not a normal feature, probably was caused by some change in Q.Config.ts that should hopefully be fixed by this commit: "
=> that shoudl be fixed. Looks like testing this it générates a 404 error when accessing this lookup.

**Comment by VictorTomaili** [comment] 2020-10-19 07:55
fixed in [3.14.2](https://www.nuget.org/packages/Serenity.Core/3.14.2)
Please open issues for related repositories. like for startsharp questions you must open issue on startsharp repository. For serenity issues you can open issue there (not questions). For other how do I? I have an error, why? questions you can use stackoverflow tag.

**Closed by VictorTomaili** 2020-10-19 07:55 UTC
