### ISSUE TITLE
Setting title of EqualityFilter is not working.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#549] opened 2016-04-09 09:47 UTC
Here is my code to set title of filter -  
`AddEqualityFilter<LookupEditor>(Fields.VoucherType, title: "Voucher Type",
                options: new LookupEditorOptions { LookupKey = VoucherTypeRow.LookupKey, MinimumResultsForSearch = 10 });`

But this is not working and still it is showing the filed display name set in row.cs.

**Comment by volkanceylan** [comment] 2016-04-09 10:50
That option only works for fields that doesn't match an actual field in database. You may do workaround for now using "voucherType" as field name instead of "VoucherType".

**Comment by ramveersgh** [comment] 2016-04-09 11:25
ok, Thanks.
I used Fields.VoucherType.ToLower() as workaround and its working.
But this is not working with
` AddDateRangeFilter(Fields.VoucherDate.ToLowerCase(), "Voucher Period");`

Display name of Fields.VoucherDate is "Date" and I want to so it as "Voucher Period". After adding ToLower its display title as 'voucherdate'

**Comment by volkanceylan** [comment] 2016-04-09 12:36
Do it with jQuery than

**Comment by volkanceylan** [comment] 2016-04-11 13:02
This should be resolved in 2.0.5

**Closed by volkanceylan** 2016-04-11 13:02 UTC

**Comment by ramveersgh** [comment] 2016-04-11 14:30
Still seems not fixed. 
Using `AddDateRangeFilter("voucherDate", "Voucher Period");` is displaying voucherDate instead of Voucher Period.

**Comment by wldkrd1** [comment] 2016-04-11 20:44
I think this is affecting all the filter types; it's no longer grabbing the NameField by default, it's grabbing the IDField.

**Comment by volkanceylan** [comment] 2016-04-11 20:48
What do you mean by grabbing ID field? For title?

**Comment by volkanceylan** [comment] 2016-04-11 20:50
Oh saw it grab me a coffee

**Comment by volkanceylan** [comment] 2016-04-11 21:12
It was due to a TypeScript change. Should be resolved with 2.0.6.

**Comment by wldkrd1** [comment] 2016-04-11 22:12
Confirmed resolved with 2.0.6, thanks!

**Comment by ramveersgh** [comment] 2016-04-12 03:19
Yes, This fixed in 2.0.6. Thanks!
