### ISSUE TITLE
CORE Beta: Contact field validation is not English

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2206] opened 2017-04-26 18:57 UTC
Running ASP.NET CORE Beta v2.9.21 with no changes from the initial install from Github. When entering a new contact the field validation hover-over is in a non-English language. General setting of app is in English.

**Comment by volkanceylan** [comment] 2017-04-26 19:57
Like the other issue, meeting is not yet finalized. Thanks.

**Comment by volkanceylan** [comment] 2017-10-19 06:48
I couldn't reproduce this issue, closing.

**Closed by volkanceylan** 2017-10-19 06:48 UTC
